server:
  port: 9999
spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    # gateway:
    #  routes:
    #    - id: r1
    #      uri: http://localhost:8080
    #      predicates:
    #        - Path= /user/**
    #    - id: r2
    #      uri: http://localhost:8081
    #      predicates:
    #        - Path= /book/**
    gateway:
      routes:
        - id: book
          uri: lb://book-service
          predicates:
            - Path=/api/books/**
        - id: user
          uri: lb://user-microservice
          predicates:
            - Path=/api/users/**
        - id: emprunt
          uri: lb://emprunt-service
          predicates:
            - Path=/api/emprunts/**
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eurika:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

